version: '3'

services:
  psql:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - psql:/var/lib/postgresql/data
    restart: always
    networks:
      - psql_net

  levels:
    build: .
    depends_on:
      - psql
    env_file:
      - .env
    environment:
      - "DB_IP=${DB_IP}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
    networks:
      - psql_net

volumes:
  psql: {}

networks:
  psql_net:
    driver: bridge
